### ISSUE TITLE
Import fails if not using pip installed PySimpleGUI

### ISSUE THREAD

**Issue by PySimpleGUI** [XavierTheCreator/YTDownloader#2]
https://github.com/XavierTheCreator/YTDownloader/blob/865443b4908b98e445a2047cb8318527707699d8/main.py#L11

I don't understand why this syntax was used on an import.  It should be just PySimpleGUI, not PySimpleGUI.PySimpleGUI.

It crashes when PySimpleGUI isn't installed via pip.  I'm guessing it was to get around some install problem you had, but it's a bad solution if it was.

**Comment by XavierTheCreator** [comment]
Not sure why that was in there but its fixed
